// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMk5I7tY_AtavXZAhemDhtjWUcNsmuMYE',
    appId: '1:552319961452:web:d879accbd118352be50b49',
    messagingSenderId: '552319961452',
    projectId: 'final-project-mobile-1',
    authDomain: 'final-project-mobile-1.firebaseapp.com',
    storageBucket: 'final-project-mobile-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQaJ3vc3kOlmNaZuB34ef75N39aYQAZ-w',
    appId: '1:552319961452:android:bdccbc48dd842e9be50b49',
    messagingSenderId: '552319961452',
    projectId: 'final-project-mobile-1',
    storageBucket: 'final-project-mobile-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSagyRijGhVKjG25BWW75ctzvJy5dA1jI',
    appId: '1:552319961452:ios:fb8f1a4e7a340714e50b49',
    messagingSenderId: '552319961452',
    projectId: 'final-project-mobile-1',
    storageBucket: 'final-project-mobile-1.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSagyRijGhVKjG25BWW75ctzvJy5dA1jI',
    appId: '1:552319961452:ios:f6453d8dccc15d75e50b49',
    messagingSenderId: '552319961452',
    projectId: 'final-project-mobile-1',
    storageBucket: 'final-project-mobile-1.appspot.com',
    iosBundleId: 'com.example.untitled2.RunnerTests',
  );
}
